[window]
decorations = "full"
opacity = 0.95
dynamic_title = true

[font]
size = 14.0
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"
