#!/usr/bin/env sh

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m signal --add event=window_destroyed action="~/.config/yabai/linux_like_spaces.sh window_destroyed"
yabai -m signal --add event=application_terminated action="~/.config/yabai/linux_like_spaces.sh window_destroyed"



# thanks to this chad https://github.com/koekeishiya/yabai/issues/213#issuecomment-2494789699
yabai -m signal --add event=space_created action='
  prev_space=$(yabai -m query --spaces --space)
  new_space=$(yabai -m query --spaces --space "$YABAI_SPACE_INDEX")
  space_id=$(jq -e "select(.\"is-native-fullscreen\") | .id" <<< "$new_space") || exit
  json_space=$(jq "{ id: $space_id, homeSpace: .id } | tojson" <<< "$prev_space")
  label=$(jq -Rr "ltrimstr(\"\\\"\") | rtrimstr(\"\\\"\")" <<< "$json_space")
  yabai -m space "$YABAI_SPACE_INDEX" --label "$label"
'

yabai -m signal --add event=space_changed action='
  home_spaces=$(yabai -m query --spaces | jq "map(.label | try fromjson | .homeSpace // empty)")
  yabai -m query --spaces \
  | jq "
      map(
        select(.windows | length == 0)
        | select(.\"has-focus\" | not)
        | select(.id as \$x | $home_spaces | index(\$x) | not)
      )
      | reverse
      | .[]
      | .index
  " \
  | xargs -I{} yabai -m space --destroy {}
'

yabai -m config \
    external_bar                 all:0:30       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  03             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^(Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Finder$" manage=off

echo "yabai configuration loaded.."
